name: Updatd docs
on:
  workflow_dispatch:
  push:
  pull_request:

permissions:
  contents: write

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - run: ./.github/builder/__main__.py
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v6.0.0
        with:
          commit_message: "Update markdown files"
