name: Updatd docs
on:
  pull_request: {}
  schedule:
    - cron: "4 2 * * *"

permissions:
  contents: write

concurrency:
  group: '${{ github.workflow }} @ ${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: ./.github/builder/__main__.py
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v6.0.1
        with:
          commit_message: "Update markdown files"
